payment_provider = "stripe"
stripe_api_key_test = "sk_test_51OkRVLKVqzJPnVbl9ZXtLksT5QMaQX7c9dWzkLBYpKcdR2NL2Kv9QDuVBLMwFeXv97ntwrpXqhyQ1xDw2Y84ZTrx00GF4Bn7JU"
stripe_api_key = "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"
stripe_link_0 = "https://buy.stripe.com/test_14kdUJ4jH21N7AIbII"
stripe_link_1 = "https://buy.stripe.com/14k5l05Sm4sd8ogfYY"
stripe_link_2 = "https://buy.stripe.com/3cscNs80u6AlgUM3cd"
stripe_link_3 = "https://buy.stripe.com/4gw28O3KeaQB33W4gi"
client_id = "620631027700-hroqcepujs3dki4duhfa3acn99gkujrn.apps.googleusercontent.com"
client_secret = "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"
redirect_url = "https://sigtrade.store/"
